name: "Theron Moto Co."
permalink: pretty
author: Theron Studios
email: hello@theronstudios.com
url: http://theronmoto.com

exclude:
  - CNAME
  - editorconfig.txt
  - Gemfile
  - Gemfile.lock
  - README.md
  - RAKEFILE

gems:
  - jekyll-assets
  - uglifier
  - sass

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  js_compressor: uglifier
  css_compressor: sass
